name: app-dev-proxy
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config:/config"
      - "./certs:/certs"
    command:
      - "--configFile=/config/traefik.yml"
networks:
  default:
    name: app-dev-mesh

