http:
  middlewares:
    cors-allow-all:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowHeaders: "*"
        accessControlAllowCredentials: true
        accessControlAllowOriginList: "*"
