api:
  insecure: true
providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/config"
entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      tls: {}
